// US States and Territories
export const US_STATES_AND_TERRITORIES = [
  // States
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "Washington D.C." },
  // Territories
  { code: "PR", name: "Puerto Rico" },
  { code: "VI", name: "U.S. Virgin Islands" },
  { code: "GU", name: "Guam" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "AS", name: "American Samoa" },
] as const;

export type StateCode = (typeof US_STATES_AND_TERRITORIES)[number]["code"];

export function getStateName(code: string): string {
  const state = US_STATES_AND_TERRITORIES.find((s) => s.code === code);
  return state?.name || code;
}

export function getStateCode(name: string): string | null {
  const state = US_STATES_AND_TERRITORIES.find(
    (s) => s.name.toLowerCase() === name.toLowerCase()
  );
  return state?.code || null;
}

// States with major cities for upload form
export const STATES_CITIES = [
  { state: "Alabama", cities: ["Birmingham", "Montgomery", "Mobile", "Huntsville"] },
  { state: "Alaska", cities: ["Anchorage", "Fairbanks", "Juneau"] },
  { state: "Arizona", cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"] },
  { state: "Arkansas", cities: ["Little Rock", "Fort Smith", "Fayetteville"] },
  { state: "California", cities: ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "Oakland", "Fresno"] },
  { state: "Colorado", cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins"] },
  { state: "Connecticut", cities: ["Hartford", "Bridgeport", "New Haven", "Stamford"] },
  { state: "Delaware", cities: ["Wilmington", "Dover"] },
  { state: "Florida", cities: ["Miami", "Tampa", "Orlando", "Jacksonville", "Fort Lauderdale"] },
  { state: "Georgia", cities: ["Atlanta", "Augusta", "Columbus", "Savannah"] },
  { state: "Hawaii", cities: ["Honolulu", "Pearl City", "Hilo"] },
  { state: "Idaho", cities: ["Boise", "Meridian", "Nampa"] },
  { state: "Illinois", cities: ["Chicago", "Aurora", "Rockford", "Joliet", "Peoria"] },
  { state: "Indiana", cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"] },
  { state: "Iowa", cities: ["Des Moines", "Cedar Rapids", "Davenport"] },
  { state: "Kansas", cities: ["Wichita", "Overland Park", "Kansas City", "Topeka"] },
  { state: "Kentucky", cities: ["Louisville", "Lexington", "Bowling Green"] },
  { state: "Louisiana", cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"] },
  { state: "Maine", cities: ["Portland", "Lewiston", "Bangor"] },
  { state: "Maryland", cities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg"] },
  { state: "Massachusetts", cities: ["Boston", "Worcester", "Springfield", "Cambridge"] },
  { state: "Michigan", cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"] },
  { state: "Minnesota", cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth"] },
  { state: "Mississippi", cities: ["Jackson", "Gulfport", "Southaven"] },
  { state: "Missouri", cities: ["Kansas City", "Saint Louis", "Springfield", "Columbia"] },
  { state: "Montana", cities: ["Billings", "Missoula", "Great Falls"] },
  { state: "Nebraska", cities: ["Omaha", "Lincoln", "Bellevue"] },
  { state: "Nevada", cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"] },
  { state: "New Hampshire", cities: ["Manchester", "Nashua", "Concord"] },
  { state: "New Jersey", cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"] },
  { state: "New Mexico", cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"] },
  { state: "New York", cities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"] },
  { state: "North Carolina", cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"] },
  { state: "North Dakota", cities: ["Fargo", "Bismarck", "Grand Forks"] },
  { state: "Ohio", cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"] },
  { state: "Oklahoma", cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"] },
  { state: "Oregon", cities: ["Portland", "Eugene", "Salem", "Gresham"] },
  { state: "Pennsylvania", cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"] },
  { state: "Rhode Island", cities: ["Providence", "Warwick", "Cranston"] },
  { state: "South Carolina", cities: ["Charleston", "Columbia", "North Charleston", "Mount Pleasant"] },
  { state: "South Dakota", cities: ["Sioux Falls", "Rapid City", "Aberdeen"] },
  { state: "Tennessee", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"] },
  { state: "Texas", cities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso"] },
  { state: "Utah", cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan"] },
  { state: "Vermont", cities: ["Burlington", "South Burlington", "Rutland"] },
  { state: "Virginia", cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria"] },
  { state: "Washington", cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"] },
  { state: "West Virginia", cities: ["Charleston", "Huntington", "Parkersburg"] },
  { state: "Wisconsin", cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha"] },
  { state: "Wyoming", cities: ["Cheyenne", "Casper", "Laramie"] },
  { state: "Washington DC", cities: ["Washington"] },
  { state: "Puerto Rico", cities: ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas", "Dorado"] },
];
